/* DO NOT EDIT! generated by ./autogen */

.intel_syntax noprefix

#include "uintbig_namespace.h"

.section .rodata

.global secsidh_internal_6143m59l262_uintbig_1
secsidh_internal_6143m59l262_uintbig_1:
    .quad 1, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0

.global secsidh_internal_6143m59l262_uintbig_1_ctidh
secsidh_internal_6143m59l262_uintbig_1_ctidh:
    .quad 1, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0

.global secsidh_internal_6143m59l262_uintbig_p
secsidh_internal_6143m59l262_uintbig_p:
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xb1a73428ffffffff, 0x3c7ea8e3c554965a
    .quad 0x40803af2fc159ef2, 0xccfb305c48d4d505, 0x6b8ef3bd24fa010d, 0x2674b4838fad59eb
    .quad 0x05c175cc1be876a7, 0xc5d744baf4074152, 0x92c4b7dd1100adfa, 0x274e59f92bd34d4d
    .quad 0x3cf8373b1a6d448d, 0x41df8b0b4f3e178b, 0x4ebfb033649a8012, 0xa4fc04deb27f0f97
    .quad 0x531b77e3e1eb32a2, 0x91707210201d3a74, 0x79dabe4d2f2a1e0f, 0x7837daa51f59cdfa
    .quad 0x91cbff70ac345b5a, 0x25223e09b7bf27c4, 0x1d384e247a3fa6bd, 0x9a2ffacba15a6110
    .quad 0x92d9ecf65f9b3fd4, 0x6c0e75f1235909ce, 0xe3945ba3564dd650, 0x79a5b88c7fe6d95f
    .quad 0x0c83174128dc676f, 0x792c81c648cab8cb, 0x12ebe4e03bcbd891, 0x251acca5a5eb867e
    .quad 0x260de537cdb28252, 0xf6f73f7357dd8f6e, 0x80480988522c5703, 0x1d8333732c8142b5
    .quad 0x305e539f114ad8ed, 0xbb6d10eb0c6c11e5, 0x4c32eab208c6e5ce, 0x4b52cce89e8e10aa

.global secsidh_internal_6143m59l262_uintbig_four_sqrt_p
secsidh_internal_6143m59l262_uintbig_four_sqrt_p:
    .quad 0xa72688f0738624ca, 0x50df7b77fbff54b0, 0xbde26e257f75eda4, 0xa13f5186be964c4f
    .quad 0x1cd52d493f2178c2, 0x85b4fa375938f823, 0x0790d5c5bc6f606e, 0xe0e5c31eda221d15
    .quad 0xdaf62df79f76df86, 0x60116bd5aca8c16a, 0x44a8858f46a75f55, 0xdb20ce98cf69e19d
    .quad 0x6d00f55a8b7ca9d6, 0xb74f00a183c3f67a, 0x5a2ea2472995aa08, 0x17eacad4c1d2a388
    .quad 0xa6269b38fbd1b856, 0x43127e32bf9cf39a, 0x2539dd9a442383d4, 0xd96d5e7265718e36
    .quad 0x38c336ccdbf682eb, 0x71d043ab1dafe28b, 0xebd5ef92fe1a9ed2, 0xe4471606dc979789
    .quad 0xea9ac8c1d078b431, 0x95fe11a7e224d95e, 0x443c9f4440f16a93, 0xe9d2efb25590a0ed
    .quad 0xd2627d46e483474a, 0xc945b1765ed52ffb, 0xc82264d987cb5fc6, 0x073a02b15ace67f3
    .quad 0xd640ab6b79e64bb4, 0xcb39339c2de7f4c6, 0x44542a41b8c8b0d1, 0xfd9232600b5a31f0
    .quad 0xb47f3f673c635d75, 0xa12af12dbb1ead94, 0xc86c2a9320a8f5ea, 0xb7cc40d96e2e9c74
    .quad 0xaf202e94fb492975, 0xd16b466497ec3db7, 0xe62ff38a9263c9ff, 0xc9fcbf4beadb34b1
    .quad 0xeea4a26f52345034, 0x5fba42e631210996, 0x9497a5698d437902, 0x2b73395a40cb4dcb
    .quad 2, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0

.section .text

.global secsidh_internal_6143m59l262_uintbig_set
secsidh_internal_6143m59l262_uintbig_set:
    cld
    mov rax, rsi
    stosq
    xor rax, rax
    mov rcx, 95
    rep stosq
    ret


.global secsidh_internal_6143m59l262_uintbig_bit
secsidh_internal_6143m59l262_uintbig_bit:
    mov rcx, rsi
    and rcx, 0x3f
    shr rsi, 6
    mov rax, [rdi + 8*rsi]
    shr rax, cl
    and rax, 1
    ret


.global secsidh_internal_6143m59l262_uintbig_add
secsidh_internal_6143m59l262_uintbig_add:
    mov rax, [rsi +  0]
    add rax, [rdx +  0]
    mov [rdi +  0], rax
    .set k, 1
    .rept 95
        mov rax, [rsi + 8*k]
        adc rax, [rdx + 8*k]
        mov [rdi + 8*k], rax
        .set k, k+1
    .endr
    setc al
    movzx rax, al
    ret

.global secsidh_internal_6143m59l262_uintbig_sub
secsidh_internal_6143m59l262_uintbig_sub:
    mov rax, [rsi +  0]
    sub rax, [rdx +  0]
    mov [rdi +  0], rax
    .set k, 1
    .rept 95
        mov rax, [rsi + 8*k]
        sbb rax, [rdx + 8*k]
        mov [rdi + 8*k], rax
        .set k, k+1
    .endr
    setc al
    movzx rax, al
    ret


.global secsidh_internal_6143m59l262_uintbig_mul3_64
secsidh_internal_6143m59l262_uintbig_mul3_64:

    mulx r10, rax, [rsi +  0]
    mov [rdi +  0], rax

    mulx r11, rax, [rsi + 8]
    add  rax, r10
    mov [rdi + 8], rax

    mulx r10, rax, [rsi + 16]
    adcx rax, r11
    mov [rdi + 16], rax

    mulx r11, rax, [rsi + 24]
    adcx rax, r10
    mov [rdi + 24], rax

    mulx r10, rax, [rsi + 32]
    adcx rax, r11
    mov [rdi + 32], rax

    mulx r11, rax, [rsi + 40]
    adcx rax, r10
    mov [rdi + 40], rax

    mulx r10, rax, [rsi + 48]
    adcx rax, r11
    mov [rdi + 48], rax

    mulx r11, rax, [rsi + 56]
    adcx rax, r10
    mov [rdi + 56], rax

    mulx r10, rax, [rsi + 64]
    adcx rax, r11
    mov [rdi + 64], rax

    mulx r11, rax, [rsi + 72]
    adcx rax, r10
    mov [rdi + 72], rax

    mulx r10, rax, [rsi + 80]
    adcx rax, r11
    mov [rdi + 80], rax

    mulx r11, rax, [rsi + 88]
    adcx rax, r10
    mov [rdi + 88], rax

    mulx r10, rax, [rsi + 96]
    adcx rax, r11
    mov [rdi + 96], rax

    mulx r11, rax, [rsi + 104]
    adcx rax, r10
    mov [rdi + 104], rax

    mulx r10, rax, [rsi + 112]
    adcx rax, r11
    mov [rdi + 112], rax

    mulx r11, rax, [rsi + 120]
    adcx rax, r10
    mov [rdi + 120], rax

    mulx r10, rax, [rsi + 128]
    adcx rax, r11
    mov [rdi + 128], rax

    mulx r11, rax, [rsi + 136]
    adcx rax, r10
    mov [rdi + 136], rax

    mulx r10, rax, [rsi + 144]
    adcx rax, r11
    mov [rdi + 144], rax

    mulx r11, rax, [rsi + 152]
    adcx rax, r10
    mov [rdi + 152], rax

    mulx r10, rax, [rsi + 160]
    adcx rax, r11
    mov [rdi + 160], rax

    mulx r11, rax, [rsi + 168]
    adcx rax, r10
    mov [rdi + 168], rax

    mulx r10, rax, [rsi + 176]
    adcx rax, r11
    mov [rdi + 176], rax

    mulx r11, rax, [rsi + 184]
    adcx rax, r10
    mov [rdi + 184], rax

    mulx r10, rax, [rsi + 192]
    adcx rax, r11
    mov [rdi + 192], rax

    mulx r11, rax, [rsi + 200]
    adcx rax, r10
    mov [rdi + 200], rax

    mulx r10, rax, [rsi + 208]
    adcx rax, r11
    mov [rdi + 208], rax

    mulx r11, rax, [rsi + 216]
    adcx rax, r10
    mov [rdi + 216], rax

    mulx r10, rax, [rsi + 224]
    adcx rax, r11
    mov [rdi + 224], rax

    mulx r11, rax, [rsi + 232]
    adcx rax, r10
    mov [rdi + 232], rax

    mulx r10, rax, [rsi + 240]
    adcx rax, r11
    mov [rdi + 240], rax

    mulx r11, rax, [rsi + 248]
    adcx rax, r10
    mov [rdi + 248], rax

    mulx r10, rax, [rsi + 256]
    adcx rax, r11
    mov [rdi + 256], rax

    mulx r11, rax, [rsi + 264]
    adcx rax, r10
    mov [rdi + 264], rax

    mulx r10, rax, [rsi + 272]
    adcx rax, r11
    mov [rdi + 272], rax

    mulx r11, rax, [rsi + 280]
    adcx rax, r10
    mov [rdi + 280], rax

    mulx r10, rax, [rsi + 288]
    adcx rax, r11
    mov [rdi + 288], rax

    mulx r11, rax, [rsi + 296]
    adcx rax, r10
    mov [rdi + 296], rax

    mulx r10, rax, [rsi + 304]
    adcx rax, r11
    mov [rdi + 304], rax

    mulx r11, rax, [rsi + 312]
    adcx rax, r10
    mov [rdi + 312], rax

    mulx r10, rax, [rsi + 320]
    adcx rax, r11
    mov [rdi + 320], rax

    mulx r11, rax, [rsi + 328]
    adcx rax, r10
    mov [rdi + 328], rax

    mulx r10, rax, [rsi + 336]
    adcx rax, r11
    mov [rdi + 336], rax

    mulx r11, rax, [rsi + 344]
    adcx rax, r10
    mov [rdi + 344], rax

    mulx r10, rax, [rsi + 352]
    adcx rax, r11
    mov [rdi + 352], rax

    mulx r11, rax, [rsi + 360]
    adcx rax, r10
    mov [rdi + 360], rax

    mulx r10, rax, [rsi + 368]
    adcx rax, r11
    mov [rdi + 368], rax

    mulx r11, rax, [rsi + 376]
    adcx rax, r10
    mov [rdi + 376], rax

    mulx r10, rax, [rsi + 384]
    adcx rax, r11
    mov [rdi + 384], rax

    mulx r11, rax, [rsi + 392]
    adcx rax, r10
    mov [rdi + 392], rax

    mulx r10, rax, [rsi + 400]
    adcx rax, r11
    mov [rdi + 400], rax

    mulx r11, rax, [rsi + 408]
    adcx rax, r10
    mov [rdi + 408], rax

    mulx r10, rax, [rsi + 416]
    adcx rax, r11
    mov [rdi + 416], rax

    mulx r11, rax, [rsi + 424]
    adcx rax, r10
    mov [rdi + 424], rax

    mulx r10, rax, [rsi + 432]
    adcx rax, r11
    mov [rdi + 432], rax

    mulx r11, rax, [rsi + 440]
    adcx rax, r10
    mov [rdi + 440], rax

    mulx r10, rax, [rsi + 448]
    adcx rax, r11
    mov [rdi + 448], rax

    mulx r11, rax, [rsi + 456]
    adcx rax, r10
    mov [rdi + 456], rax

    mulx r10, rax, [rsi + 464]
    adcx rax, r11
    mov [rdi + 464], rax

    mulx r11, rax, [rsi + 472]
    adcx rax, r10
    mov [rdi + 472], rax

    mulx r10, rax, [rsi + 480]
    adcx rax, r11
    mov [rdi + 480], rax

    mulx r11, rax, [rsi + 488]
    adcx rax, r10
    mov [rdi + 488], rax

    mulx r10, rax, [rsi + 496]
    adcx rax, r11
    mov [rdi + 496], rax

    mulx r11, rax, [rsi + 504]
    adcx rax, r10
    mov [rdi + 504], rax

    mulx r10, rax, [rsi + 512]
    adcx rax, r11
    mov [rdi + 512], rax

    mulx r11, rax, [rsi + 520]
    adcx rax, r10
    mov [rdi + 520], rax

    mulx r10, rax, [rsi + 528]
    adcx rax, r11
    mov [rdi + 528], rax

    mulx r11, rax, [rsi + 536]
    adcx rax, r10
    mov [rdi + 536], rax

    mulx r10, rax, [rsi + 544]
    adcx rax, r11
    mov [rdi + 544], rax

    mulx r11, rax, [rsi + 552]
    adcx rax, r10
    mov [rdi + 552], rax

    mulx r10, rax, [rsi + 560]
    adcx rax, r11
    mov [rdi + 560], rax

    mulx r11, rax, [rsi + 568]
    adcx rax, r10
    mov [rdi + 568], rax

    mulx r10, rax, [rsi + 576]
    adcx rax, r11
    mov [rdi + 576], rax

    mulx r11, rax, [rsi + 584]
    adcx rax, r10
    mov [rdi + 584], rax

    mulx r10, rax, [rsi + 592]
    adcx rax, r11
    mov [rdi + 592], rax

    mulx r11, rax, [rsi + 600]
    adcx rax, r10
    mov [rdi + 600], rax

    mulx r10, rax, [rsi + 608]
    adcx rax, r11
    mov [rdi + 608], rax

    mulx r11, rax, [rsi + 616]
    adcx rax, r10
    mov [rdi + 616], rax

    mulx r10, rax, [rsi + 624]
    adcx rax, r11
    mov [rdi + 624], rax

    mulx r11, rax, [rsi + 632]
    adcx rax, r10
    mov [rdi + 632], rax

    mulx r10, rax, [rsi + 640]
    adcx rax, r11
    mov [rdi + 640], rax

    mulx r11, rax, [rsi + 648]
    adcx rax, r10
    mov [rdi + 648], rax

    mulx r10, rax, [rsi + 656]
    adcx rax, r11
    mov [rdi + 656], rax

    mulx r11, rax, [rsi + 664]
    adcx rax, r10
    mov [rdi + 664], rax

    mulx r10, rax, [rsi + 672]
    adcx rax, r11
    mov [rdi + 672], rax

    mulx r11, rax, [rsi + 680]
    adcx rax, r10
    mov [rdi + 680], rax

    mulx r10, rax, [rsi + 688]
    adcx rax, r11
    mov [rdi + 688], rax

    mulx r11, rax, [rsi + 696]
    adcx rax, r10
    mov [rdi + 696], rax

    mulx r10, rax, [rsi + 704]
    adcx rax, r11
    mov [rdi + 704], rax

    mulx r11, rax, [rsi + 712]
    adcx rax, r10
    mov [rdi + 712], rax

    mulx r10, rax, [rsi + 720]
    adcx rax, r11
    mov [rdi + 720], rax

    mulx r11, rax, [rsi + 728]
    adcx rax, r10
    mov [rdi + 728], rax

    mulx r10, rax, [rsi + 736]
    adcx rax, r11
    mov [rdi + 736], rax

    mulx r11, rax, [rsi + 744]
    adcx rax, r10
    mov [rdi + 744], rax

    mulx r10, rax, [rsi + 752]
    adcx rax, r11
    mov [rdi + 752], rax

    mulx r11, rax, [rsi + 760]
    adcx rax, r10
    mov [rdi + 760], rax

    ret
