/* DO NOT EDIT! generated by ./autogen */

.intel_syntax noprefix

#include "uintbig_namespace.h"

.section .rodata

.global secsidh_internal_5119m46l244_uintbig_1
secsidh_internal_5119m46l244_uintbig_1:
    .quad 1, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0

.global secsidh_internal_5119m46l244_uintbig_1_ctidh
secsidh_internal_5119m46l244_uintbig_1_ctidh:
    .quad 1, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0

.global secsidh_internal_5119m46l244_uintbig_p
secsidh_internal_5119m46l244_uintbig_p:
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0x31c122b2ffffffff, 0x71bab792ccf26c33, 0xf100763480d81d65
    .quad 0x0a2a4d3afcd84cb1, 0xa5277c5a1edf4274, 0x83b80791506a02be, 0x099a550e13c0f216
    .quad 0xb269f7eff29ee16b, 0x4433973b01a89610, 0x321da18b685fa986, 0x257f8cbb1ad63459
    .quad 0x8b0742f099c755e4, 0x182dc9e83cc912b1, 0xb30d2e40db42513a, 0x080643c752d3f0bf
    .quad 0xb1fe257416d05092, 0x4df7cbb62e4281f0, 0xa1160ac1b85c89ad, 0x4a2e0b5d9e3d744a
    .quad 0x966a6c73f126a7fa, 0x0d2257bed2c00854, 0x4a4bf83147c01f3a, 0xd9059c466ba6095b
    .quad 0xcba1d52981546d14, 0x3eb030efe24f606e, 0x1aedff7abbd03380, 0x5d98ddb04f236ac6
    .quad 0x1f166b7a23e849b5, 0x25529cd9b432f707, 0xc76f78378b762434, 0x994de9fa51639c1d
    .quad 0x4907fb14725711f2, 0x2132f7b67412060b, 0x93a14a8a040ecbd4, 0x6020eb29a152ad5f

.global secsidh_internal_5119m46l244_uintbig_four_sqrt_p
secsidh_internal_5119m46l244_uintbig_four_sqrt_p:
    .quad 0x18d50bdb145e34d7, 0x416ddf55e8d234ad, 0xacdd45438e5834d2, 0x36edfa22acf89a0a
    .quad 0x014644d4cde9971c, 0xbf839772fe83f303, 0x1c2b0c55bae5cd17, 0x86c9e6f505c3c684
    .quad 0x24eb43c396b8f6b4, 0x4f9721780fb3ad68, 0xa51400378743474d, 0xc8bfc91911b1370a
    .quad 0x34916680b87fd24f, 0x8015c71fa0ee790f, 0x3d1e5b2937c139d1, 0x1e303af1e6b0addb
    .quad 0x5ebf5644cbad54d1, 0xc77f3e6624b77cf4, 0xe99385c122f3623f, 0x226f7589a8e6a89e
    .quad 0x509ad5b2d8300a49, 0x5aa6746b9c534abc, 0xd800c27ac9c85ee5, 0xebc7ffb0c90cfa53
    .quad 0x0f571e017ac788ef, 0xcc49cad1c91455d6, 0xc659c18330326150, 0xdbf2850631962bd0
    .quad 0x02fab9abbc108f7d, 0xca4bf6b0af4433c4, 0xba94944b61f5fab2, 0x6989efd3cdd039aa
    .quad 0xc188c4b69f145510, 0xc559edc12978a98f, 0xf92d2a903b961472, 0xd0315aedc1b4e351
    .quad 0x1e831dc3c87c37e7, 0xdbe749f8106d5e96, 0x62b3c02ed939a84a, 0x737d3c4abf7bdbf4
    .quad 2, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0

.section .text

.global secsidh_internal_5119m46l244_uintbig_set
secsidh_internal_5119m46l244_uintbig_set:
    cld
    mov rax, rsi
    stosq
    xor rax, rax
    mov rcx, 79
    rep stosq
    ret


.global secsidh_internal_5119m46l244_uintbig_bit
secsidh_internal_5119m46l244_uintbig_bit:
    mov rcx, rsi
    and rcx, 0x3f
    shr rsi, 6
    mov rax, [rdi + 8*rsi]
    shr rax, cl
    and rax, 1
    ret


.global secsidh_internal_5119m46l244_uintbig_add
secsidh_internal_5119m46l244_uintbig_add:
    mov rax, [rsi +  0]
    add rax, [rdx +  0]
    mov [rdi +  0], rax
    .set k, 1
    .rept 79
        mov rax, [rsi + 8*k]
        adc rax, [rdx + 8*k]
        mov [rdi + 8*k], rax
        .set k, k+1
    .endr
    setc al
    movzx rax, al
    ret

.global secsidh_internal_5119m46l244_uintbig_sub
secsidh_internal_5119m46l244_uintbig_sub:
    mov rax, [rsi +  0]
    sub rax, [rdx +  0]
    mov [rdi +  0], rax
    .set k, 1
    .rept 79
        mov rax, [rsi + 8*k]
        sbb rax, [rdx + 8*k]
        mov [rdi + 8*k], rax
        .set k, k+1
    .endr
    setc al
    movzx rax, al
    ret


.global secsidh_internal_5119m46l244_uintbig_mul3_64
secsidh_internal_5119m46l244_uintbig_mul3_64:

    mulx r10, rax, [rsi +  0]
    mov [rdi +  0], rax

    mulx r11, rax, [rsi + 8]
    add  rax, r10
    mov [rdi + 8], rax

    mulx r10, rax, [rsi + 16]
    adcx rax, r11
    mov [rdi + 16], rax

    mulx r11, rax, [rsi + 24]
    adcx rax, r10
    mov [rdi + 24], rax

    mulx r10, rax, [rsi + 32]
    adcx rax, r11
    mov [rdi + 32], rax

    mulx r11, rax, [rsi + 40]
    adcx rax, r10
    mov [rdi + 40], rax

    mulx r10, rax, [rsi + 48]
    adcx rax, r11
    mov [rdi + 48], rax

    mulx r11, rax, [rsi + 56]
    adcx rax, r10
    mov [rdi + 56], rax

    mulx r10, rax, [rsi + 64]
    adcx rax, r11
    mov [rdi + 64], rax

    mulx r11, rax, [rsi + 72]
    adcx rax, r10
    mov [rdi + 72], rax

    mulx r10, rax, [rsi + 80]
    adcx rax, r11
    mov [rdi + 80], rax

    mulx r11, rax, [rsi + 88]
    adcx rax, r10
    mov [rdi + 88], rax

    mulx r10, rax, [rsi + 96]
    adcx rax, r11
    mov [rdi + 96], rax

    mulx r11, rax, [rsi + 104]
    adcx rax, r10
    mov [rdi + 104], rax

    mulx r10, rax, [rsi + 112]
    adcx rax, r11
    mov [rdi + 112], rax

    mulx r11, rax, [rsi + 120]
    adcx rax, r10
    mov [rdi + 120], rax

    mulx r10, rax, [rsi + 128]
    adcx rax, r11
    mov [rdi + 128], rax

    mulx r11, rax, [rsi + 136]
    adcx rax, r10
    mov [rdi + 136], rax

    mulx r10, rax, [rsi + 144]
    adcx rax, r11
    mov [rdi + 144], rax

    mulx r11, rax, [rsi + 152]
    adcx rax, r10
    mov [rdi + 152], rax

    mulx r10, rax, [rsi + 160]
    adcx rax, r11
    mov [rdi + 160], rax

    mulx r11, rax, [rsi + 168]
    adcx rax, r10
    mov [rdi + 168], rax

    mulx r10, rax, [rsi + 176]
    adcx rax, r11
    mov [rdi + 176], rax

    mulx r11, rax, [rsi + 184]
    adcx rax, r10
    mov [rdi + 184], rax

    mulx r10, rax, [rsi + 192]
    adcx rax, r11
    mov [rdi + 192], rax

    mulx r11, rax, [rsi + 200]
    adcx rax, r10
    mov [rdi + 200], rax

    mulx r10, rax, [rsi + 208]
    adcx rax, r11
    mov [rdi + 208], rax

    mulx r11, rax, [rsi + 216]
    adcx rax, r10
    mov [rdi + 216], rax

    mulx r10, rax, [rsi + 224]
    adcx rax, r11
    mov [rdi + 224], rax

    mulx r11, rax, [rsi + 232]
    adcx rax, r10
    mov [rdi + 232], rax

    mulx r10, rax, [rsi + 240]
    adcx rax, r11
    mov [rdi + 240], rax

    mulx r11, rax, [rsi + 248]
    adcx rax, r10
    mov [rdi + 248], rax

    mulx r10, rax, [rsi + 256]
    adcx rax, r11
    mov [rdi + 256], rax

    mulx r11, rax, [rsi + 264]
    adcx rax, r10
    mov [rdi + 264], rax

    mulx r10, rax, [rsi + 272]
    adcx rax, r11
    mov [rdi + 272], rax

    mulx r11, rax, [rsi + 280]
    adcx rax, r10
    mov [rdi + 280], rax

    mulx r10, rax, [rsi + 288]
    adcx rax, r11
    mov [rdi + 288], rax

    mulx r11, rax, [rsi + 296]
    adcx rax, r10
    mov [rdi + 296], rax

    mulx r10, rax, [rsi + 304]
    adcx rax, r11
    mov [rdi + 304], rax

    mulx r11, rax, [rsi + 312]
    adcx rax, r10
    mov [rdi + 312], rax

    mulx r10, rax, [rsi + 320]
    adcx rax, r11
    mov [rdi + 320], rax

    mulx r11, rax, [rsi + 328]
    adcx rax, r10
    mov [rdi + 328], rax

    mulx r10, rax, [rsi + 336]
    adcx rax, r11
    mov [rdi + 336], rax

    mulx r11, rax, [rsi + 344]
    adcx rax, r10
    mov [rdi + 344], rax

    mulx r10, rax, [rsi + 352]
    adcx rax, r11
    mov [rdi + 352], rax

    mulx r11, rax, [rsi + 360]
    adcx rax, r10
    mov [rdi + 360], rax

    mulx r10, rax, [rsi + 368]
    adcx rax, r11
    mov [rdi + 368], rax

    mulx r11, rax, [rsi + 376]
    adcx rax, r10
    mov [rdi + 376], rax

    mulx r10, rax, [rsi + 384]
    adcx rax, r11
    mov [rdi + 384], rax

    mulx r11, rax, [rsi + 392]
    adcx rax, r10
    mov [rdi + 392], rax

    mulx r10, rax, [rsi + 400]
    adcx rax, r11
    mov [rdi + 400], rax

    mulx r11, rax, [rsi + 408]
    adcx rax, r10
    mov [rdi + 408], rax

    mulx r10, rax, [rsi + 416]
    adcx rax, r11
    mov [rdi + 416], rax

    mulx r11, rax, [rsi + 424]
    adcx rax, r10
    mov [rdi + 424], rax

    mulx r10, rax, [rsi + 432]
    adcx rax, r11
    mov [rdi + 432], rax

    mulx r11, rax, [rsi + 440]
    adcx rax, r10
    mov [rdi + 440], rax

    mulx r10, rax, [rsi + 448]
    adcx rax, r11
    mov [rdi + 448], rax

    mulx r11, rax, [rsi + 456]
    adcx rax, r10
    mov [rdi + 456], rax

    mulx r10, rax, [rsi + 464]
    adcx rax, r11
    mov [rdi + 464], rax

    mulx r11, rax, [rsi + 472]
    adcx rax, r10
    mov [rdi + 472], rax

    mulx r10, rax, [rsi + 480]
    adcx rax, r11
    mov [rdi + 480], rax

    mulx r11, rax, [rsi + 488]
    adcx rax, r10
    mov [rdi + 488], rax

    mulx r10, rax, [rsi + 496]
    adcx rax, r11
    mov [rdi + 496], rax

    mulx r11, rax, [rsi + 504]
    adcx rax, r10
    mov [rdi + 504], rax

    mulx r10, rax, [rsi + 512]
    adcx rax, r11
    mov [rdi + 512], rax

    mulx r11, rax, [rsi + 520]
    adcx rax, r10
    mov [rdi + 520], rax

    mulx r10, rax, [rsi + 528]
    adcx rax, r11
    mov [rdi + 528], rax

    mulx r11, rax, [rsi + 536]
    adcx rax, r10
    mov [rdi + 536], rax

    mulx r10, rax, [rsi + 544]
    adcx rax, r11
    mov [rdi + 544], rax

    mulx r11, rax, [rsi + 552]
    adcx rax, r10
    mov [rdi + 552], rax

    mulx r10, rax, [rsi + 560]
    adcx rax, r11
    mov [rdi + 560], rax

    mulx r11, rax, [rsi + 568]
    adcx rax, r10
    mov [rdi + 568], rax

    mulx r10, rax, [rsi + 576]
    adcx rax, r11
    mov [rdi + 576], rax

    mulx r11, rax, [rsi + 584]
    adcx rax, r10
    mov [rdi + 584], rax

    mulx r10, rax, [rsi + 592]
    adcx rax, r11
    mov [rdi + 592], rax

    mulx r11, rax, [rsi + 600]
    adcx rax, r10
    mov [rdi + 600], rax

    mulx r10, rax, [rsi + 608]
    adcx rax, r11
    mov [rdi + 608], rax

    mulx r11, rax, [rsi + 616]
    adcx rax, r10
    mov [rdi + 616], rax

    mulx r10, rax, [rsi + 624]
    adcx rax, r11
    mov [rdi + 624], rax

    mulx r11, rax, [rsi + 632]
    adcx rax, r10
    mov [rdi + 632], rax

    ret
