/* DO NOT EDIT! generated by ./autogen */

.intel_syntax noprefix

#include "uintbig_namespace.h"

.section .rodata

.global secsidh_internal_4095m27l262_uintbig_1
secsidh_internal_4095m27l262_uintbig_1:
    .quad 1, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0

.global secsidh_internal_4095m27l262_uintbig_1_ctidh
secsidh_internal_4095m27l262_uintbig_1_ctidh:
    .quad 1, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0

.global secsidh_internal_4095m27l262_uintbig_p
secsidh_internal_4095m27l262_uintbig_p:
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0x3b78d7b10f1cb8f4, 0x65888c198a8e59fb
    .quad 0x69596010d2245505, 0xfb85d331bf15dbf3, 0x37972594a6c994ee, 0x96fe98e120b09bc3
    .quad 0x58bd5bbba27779bc, 0xd3f92a67c4103933, 0x31e5ff951b6d7341, 0x0dbdce9c5b4a495f
    .quad 0xf7f6282402f363a1, 0x3b060db5e11ab944, 0x4ec8b118af8dbc53, 0xdde49f6161571fd8
    .quad 0x71157d20bf37675a, 0x797e5708f727ed74, 0x2321418bc30a539a, 0xa44fa639976ac4e7
    .quad 0x91c11928b06e3fbe, 0x4cb0c8f4d65a4621, 0x8b8d69e7ac15ec05, 0xaf581dad341e7736
    .quad 0x6797c15ade6fc067, 0x920fad0ab8c53dec, 0xc1e76d615c55d39c, 0xeb058573ce240f88
    .quad 0xa556349d51ff4f46, 0x62f3fcac66d97c78, 0x5f9b0d210c56f8f0, 0xab53247f88df7f7a
    .quad 0x94116953ce9e76ff, 0xa22108fbbf709ebf, 0xb961c86b9ab57c35, 0x533f33caa89e8487
    .quad 0x608d0ff735d0abb9, 0xaade61945f8ae99f, 0x627b08feb90a8490, 0x47df1bed926b3ac9

.global secsidh_internal_4095m27l262_uintbig_four_sqrt_p
secsidh_internal_4095m27l262_uintbig_four_sqrt_p:
    .quad 0xb5da908efb3a61c1, 0x2c9a4d0740a605c1, 0x54793951c25627a7, 0x9d229b24d81753f6
    .quad 0x24d00c737a3ec0b9, 0xec546c7b78f2afb2, 0x636ee25be9ef7867, 0xdd38d387b1a64899
    .quad 0x3620e988fb324b64, 0xc1b3652a7861f4e8, 0x2de25f400e419c2c, 0x11fc7661be9a3983
    .quad 0xbe3b2fa57f1b25d1, 0xbd63f9c44a3388c6, 0x810eb21664fb1d7f, 0x4fafcfc74b0a0cbd
    .quad 0xdc7a8ac9a4c4e737, 0x1d85cb754d96c8df, 0x1a92556755ef8e9e, 0xa1fea7497f96f5d6
    .quad 0x1f16746367edf379, 0xcadb564e24c3cd49, 0xee84e1ed47232d3e, 0x25bc28f11faaca1c
    .quad 0x6449e03db9099292, 0x8a74be1a0063db91, 0x9884bf3ecbcb2b93, 0xc05d23071f49e4a3
    .quad 0xb02a6e45eacbd76e, 0x261701186273e6bc, 0x3f6cc8ea0e0024a0, 0x1e92c159c04e604c
    .quad 2, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0

.section .text

.global secsidh_internal_4095m27l262_uintbig_set
secsidh_internal_4095m27l262_uintbig_set:
    cld
    mov rax, rsi
    stosq
    xor rax, rax
    mov rcx, 63
    rep stosq
    ret


.global secsidh_internal_4095m27l262_uintbig_bit
secsidh_internal_4095m27l262_uintbig_bit:
    mov rcx, rsi
    and rcx, 0x3f
    shr rsi, 6
    mov rax, [rdi + 8*rsi]
    shr rax, cl
    and rax, 1
    ret


.global secsidh_internal_4095m27l262_uintbig_add
secsidh_internal_4095m27l262_uintbig_add:
    mov rax, [rsi +  0]
    add rax, [rdx +  0]
    mov [rdi +  0], rax
    .set k, 1
    .rept 63
        mov rax, [rsi + 8*k]
        adc rax, [rdx + 8*k]
        mov [rdi + 8*k], rax
        .set k, k+1
    .endr
    setc al
    movzx rax, al
    ret

.global secsidh_internal_4095m27l262_uintbig_sub
secsidh_internal_4095m27l262_uintbig_sub:
    mov rax, [rsi +  0]
    sub rax, [rdx +  0]
    mov [rdi +  0], rax
    .set k, 1
    .rept 63
        mov rax, [rsi + 8*k]
        sbb rax, [rdx + 8*k]
        mov [rdi + 8*k], rax
        .set k, k+1
    .endr
    setc al
    movzx rax, al
    ret


.global secsidh_internal_4095m27l262_uintbig_mul3_64
secsidh_internal_4095m27l262_uintbig_mul3_64:

    mulx r10, rax, [rsi +  0]
    mov [rdi +  0], rax

    mulx r11, rax, [rsi + 8]
    add  rax, r10
    mov [rdi + 8], rax

    mulx r10, rax, [rsi + 16]
    adcx rax, r11
    mov [rdi + 16], rax

    mulx r11, rax, [rsi + 24]
    adcx rax, r10
    mov [rdi + 24], rax

    mulx r10, rax, [rsi + 32]
    adcx rax, r11
    mov [rdi + 32], rax

    mulx r11, rax, [rsi + 40]
    adcx rax, r10
    mov [rdi + 40], rax

    mulx r10, rax, [rsi + 48]
    adcx rax, r11
    mov [rdi + 48], rax

    mulx r11, rax, [rsi + 56]
    adcx rax, r10
    mov [rdi + 56], rax

    mulx r10, rax, [rsi + 64]
    adcx rax, r11
    mov [rdi + 64], rax

    mulx r11, rax, [rsi + 72]
    adcx rax, r10
    mov [rdi + 72], rax

    mulx r10, rax, [rsi + 80]
    adcx rax, r11
    mov [rdi + 80], rax

    mulx r11, rax, [rsi + 88]
    adcx rax, r10
    mov [rdi + 88], rax

    mulx r10, rax, [rsi + 96]
    adcx rax, r11
    mov [rdi + 96], rax

    mulx r11, rax, [rsi + 104]
    adcx rax, r10
    mov [rdi + 104], rax

    mulx r10, rax, [rsi + 112]
    adcx rax, r11
    mov [rdi + 112], rax

    mulx r11, rax, [rsi + 120]
    adcx rax, r10
    mov [rdi + 120], rax

    mulx r10, rax, [rsi + 128]
    adcx rax, r11
    mov [rdi + 128], rax

    mulx r11, rax, [rsi + 136]
    adcx rax, r10
    mov [rdi + 136], rax

    mulx r10, rax, [rsi + 144]
    adcx rax, r11
    mov [rdi + 144], rax

    mulx r11, rax, [rsi + 152]
    adcx rax, r10
    mov [rdi + 152], rax

    mulx r10, rax, [rsi + 160]
    adcx rax, r11
    mov [rdi + 160], rax

    mulx r11, rax, [rsi + 168]
    adcx rax, r10
    mov [rdi + 168], rax

    mulx r10, rax, [rsi + 176]
    adcx rax, r11
    mov [rdi + 176], rax

    mulx r11, rax, [rsi + 184]
    adcx rax, r10
    mov [rdi + 184], rax

    mulx r10, rax, [rsi + 192]
    adcx rax, r11
    mov [rdi + 192], rax

    mulx r11, rax, [rsi + 200]
    adcx rax, r10
    mov [rdi + 200], rax

    mulx r10, rax, [rsi + 208]
    adcx rax, r11
    mov [rdi + 208], rax

    mulx r11, rax, [rsi + 216]
    adcx rax, r10
    mov [rdi + 216], rax

    mulx r10, rax, [rsi + 224]
    adcx rax, r11
    mov [rdi + 224], rax

    mulx r11, rax, [rsi + 232]
    adcx rax, r10
    mov [rdi + 232], rax

    mulx r10, rax, [rsi + 240]
    adcx rax, r11
    mov [rdi + 240], rax

    mulx r11, rax, [rsi + 248]
    adcx rax, r10
    mov [rdi + 248], rax

    mulx r10, rax, [rsi + 256]
    adcx rax, r11
    mov [rdi + 256], rax

    mulx r11, rax, [rsi + 264]
    adcx rax, r10
    mov [rdi + 264], rax

    mulx r10, rax, [rsi + 272]
    adcx rax, r11
    mov [rdi + 272], rax

    mulx r11, rax, [rsi + 280]
    adcx rax, r10
    mov [rdi + 280], rax

    mulx r10, rax, [rsi + 288]
    adcx rax, r11
    mov [rdi + 288], rax

    mulx r11, rax, [rsi + 296]
    adcx rax, r10
    mov [rdi + 296], rax

    mulx r10, rax, [rsi + 304]
    adcx rax, r11
    mov [rdi + 304], rax

    mulx r11, rax, [rsi + 312]
    adcx rax, r10
    mov [rdi + 312], rax

    mulx r10, rax, [rsi + 320]
    adcx rax, r11
    mov [rdi + 320], rax

    mulx r11, rax, [rsi + 328]
    adcx rax, r10
    mov [rdi + 328], rax

    mulx r10, rax, [rsi + 336]
    adcx rax, r11
    mov [rdi + 336], rax

    mulx r11, rax, [rsi + 344]
    adcx rax, r10
    mov [rdi + 344], rax

    mulx r10, rax, [rsi + 352]
    adcx rax, r11
    mov [rdi + 352], rax

    mulx r11, rax, [rsi + 360]
    adcx rax, r10
    mov [rdi + 360], rax

    mulx r10, rax, [rsi + 368]
    adcx rax, r11
    mov [rdi + 368], rax

    mulx r11, rax, [rsi + 376]
    adcx rax, r10
    mov [rdi + 376], rax

    mulx r10, rax, [rsi + 384]
    adcx rax, r11
    mov [rdi + 384], rax

    mulx r11, rax, [rsi + 392]
    adcx rax, r10
    mov [rdi + 392], rax

    mulx r10, rax, [rsi + 400]
    adcx rax, r11
    mov [rdi + 400], rax

    mulx r11, rax, [rsi + 408]
    adcx rax, r10
    mov [rdi + 408], rax

    mulx r10, rax, [rsi + 416]
    adcx rax, r11
    mov [rdi + 416], rax

    mulx r11, rax, [rsi + 424]
    adcx rax, r10
    mov [rdi + 424], rax

    mulx r10, rax, [rsi + 432]
    adcx rax, r11
    mov [rdi + 432], rax

    mulx r11, rax, [rsi + 440]
    adcx rax, r10
    mov [rdi + 440], rax

    mulx r10, rax, [rsi + 448]
    adcx rax, r11
    mov [rdi + 448], rax

    mulx r11, rax, [rsi + 456]
    adcx rax, r10
    mov [rdi + 456], rax

    mulx r10, rax, [rsi + 464]
    adcx rax, r11
    mov [rdi + 464], rax

    mulx r11, rax, [rsi + 472]
    adcx rax, r10
    mov [rdi + 472], rax

    mulx r10, rax, [rsi + 480]
    adcx rax, r11
    mov [rdi + 480], rax

    mulx r11, rax, [rsi + 488]
    adcx rax, r10
    mov [rdi + 488], rax

    mulx r10, rax, [rsi + 496]
    adcx rax, r11
    mov [rdi + 496], rax

    mulx r11, rax, [rsi + 504]
    adcx rax, r10
    mov [rdi + 504], rax

    ret
