/* DO NOT EDIT! generated by ./autogen */

.intel_syntax noprefix

#include "uintbig_namespace.h"

.section .rodata

.global secsidh_internal_8191m78l338_uintbig_1
secsidh_internal_8191m78l338_uintbig_1:
    .quad 1, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0

.global secsidh_internal_8191m78l338_uintbig_1_ctidh
secsidh_internal_8191m78l338_uintbig_1_ctidh:
    .quad 1, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0


.global secsidh_internal_8191m78l338_uintbig_p
secsidh_internal_8191m78l338_uintbig_p:
.quad 0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF 
.quad 0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF 
.quad 0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF 
.quad 0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF 
.quad 0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF 
.quad 0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF 
.quad 0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF 
.quad 0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF 
.quad 0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF 
.quad 0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF 
.quad 0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF 
.quad 0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF 
.quad 0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF 
.quad 0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF 
.quad 0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF 
.quad 0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF 
.quad 0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF 
.quad 0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF 
.quad 0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF 
.quad 0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFF,0x3EAF65A95F0041EC,0x372B7D9154133882 
.quad 0x5A58A580E1CA9829,0x8FC4156DDCAD437,0x4CE6AE3C63765131,0x4F3865F90F46D0D3 
.quad 0xB6AA2C454C34E51B,0xD434D3F80A147B77,0x6B926F74A2AA5C76,0x43BCB530BDFEAFF9 
.quad 0x671D6CE9572B43C1,0xD5B30D80ECB73020,0xF823265621739F49,0xC1754744306061CA 
.quad 0x6171E42D89E177BB,0x8994F48EF23A7F2A,0xA2057C82B399C3AF,0xC60CD8BEC9D528B1 
.quad 0xB9B5FAB739469676,0x601A2E4779AEC853,0xE00D857E16B58377,0xE65DEF66D0C08A1D 
.quad 0x26692BC11E11E82B,0x3A2B8F6CD365560D,0x39E653855729C7FB,0xC10B3B5E0D9DE1C4 
.quad 0x7D13530314EEC59E,0xD0A1B556BFEAF779,0xE63C16F48D4938B9,0x3839DF74876C52B0 
.quad 0x5AD0EACB1BD7283,0xC1709D8F85717F0F,0x185BC2F57DE71EB1,0x2F9EC8170F78D4E0 
.quad 0xF519D562D85DB142,0x9CCB77F2238053C5,0x6BB5CF773506E8B0,0x2770E39BEED00FEB 
.quad 0x3A51E0099D663BC,0x5E93F3908FA8986E,0x4AE63438608085B,0x5290F3FDF0F9F666 
.quad 0xA5E5B7F7D86B7F44,0xAB4BD70919AC3458,0x60473AD832847641,0xC35589BD7E5B6D68 
.quad 0x60340C810D6E6475,0xDA4E9331BBBE84E,0x8726969D65FA39A0,0x558064826AE53F6C 

# .global secsidh_internal_8191m78l338_uintbig_four_sqrt_p
# secsidh_internal_8191m78l338_uintbig_four_sqrt_p:
#     .quad 0xe9b11db95ef193f2, 0x30553f998ab6c27b, 0x60f5c93ebe1a3568, 0xa36c269ea584b133
#     .quad 0x1bf5506f916eb001, 0x3421327dcabe0bcd, 0xf3c46366b5d12dd8, 0xdeb700cee24e76a1
#     .quad 0x7eefc03e6d984743, 0xf8cadb22fe0c965c, 0xd353b1bc2cc339e6, 0xacfc9a9ad5452eb3
#     .quad 0x8a4ac38cc9c15d89, 0xb907fb27cd12087c, 0x36032a31cab92ce6, 0xc3f2123af976eab2
#     .quad 0x11b492210e76923d, 0x8a82c90c4e226449, 0xce916d6caf1fbe77, 0xb4276b5393c12733
#     .quad 0x0f04003e92b15712, 0x00c1f13074d80105, 0x2c0fc2fe44bbe55d, 0xdf29818f93b39741
#     .quad 0x5581ff24f8767959, 0xf089ace0f2ddf88f, 0xdd4c14275e15bbb9, 0x28e7c5078b7046a1
#     .quad 0x7a4af8c4c73fd368, 0x918e3a440f8c00ea, 0xa0af5a549ff688b0, 0xfd7b0be0b91e970b
#     .quad 0x57d0cff564cf3e16, 0x0989e9bad743d1e1, 0x66b7bd9218c74be0, 0xafa4a16ab218a590
#     .quad 0xd033f31ff8ded775, 0xe2664c0fec871f23, 0x822bcb930224b790, 0x9d45996f90b5da1f
#     .quad 0xead38323a426d544, 0x3ec25b466dde7ba5, 0x831a592739d133d7, 0xe699dbe425b50044
#     .quad 0xd695f39922806281, 0x27474294667c33e5, 0x90ba4e66c647b571, 0x92f15bb238f58d4f
#     .quad 0x2b73d07963dbaea2, 0x23475a3bbfb0fddc, 0x8c562bb91bb01430, 0xcb2e9ab8af14a037
#     .quad 0x5b52bddcac1bdfa1, 0x5e0320cc21fb9b9c, 0x616f49583271c49b, 0x63da2797a57f09e3
#     .quad 0x8544281023c7d3f1, 0x16da583576e8c1c9, 0x731ab8262614bd82, 0xe1c3c4b5d07918ef
#     .quad 0xcf9fc55bed50f5f0, 0x65f62328293bf71e, 0x9c90b00fc8b52948, 0x158c96f23435177c
#     .quad 2, 0, 0, 0
#     .quad 0, 0, 0, 0
#     .quad 0, 0, 0, 0
#     .quad 0, 0, 0, 0
#     .quad 0, 0, 0, 0
#     .quad 0, 0, 0, 0
#     .quad 0, 0, 0, 0
#     .quad 0, 0, 0, 0
#     .quad 0, 0, 0, 0
#     .quad 0, 0, 0, 0
#     .quad 0, 0, 0, 0
#     .quad 0, 0, 0, 0
#     .quad 0, 0, 0, 0
#     .quad 0, 0, 0, 0
#     .quad 0, 0, 0, 0
#     .quad 0, 0, 0, 0

.section .text

.global secsidh_internal_8191m78l338_uintbig_set
secsidh_internal_8191m78l338_uintbig_set:
    cld
    mov rax, rsi
    stosq
    xor rax, rax
    mov rcx, 127
    rep stosq
    ret


.global secsidh_internal_8191m78l338_uintbig_bit
secsidh_internal_8191m78l338_uintbig_bit:
    mov rcx, rsi
    and rcx, 0x3f
    shr rsi, 6
    mov rax, [rdi + 8*rsi]
    shr rax, cl
    and rax, 1
    ret


.global secsidh_internal_8191m78l338_uintbig_add
secsidh_internal_8191m78l338_uintbig_add:
    mov rax, [rsi +  0]
    add rax, [rdx +  0]
    mov [rdi +  0], rax
    .set k, 1
    .rept 127
        mov rax, [rsi + 8*k]
        adc rax, [rdx + 8*k]
        mov [rdi + 8*k], rax
        .set k, k+1
    .endr
    setc al
    movzx rax, al
    ret

.global secsidh_internal_8191m78l338_uintbig_sub3
secsidh_internal_8191m78l338_uintbig_sub3:
.global secsidh_internal_8191m78l338_uintbig_sub
secsidh_internal_8191m78l338_uintbig_sub:
    mov rax, [rsi +  0]
    sub rax, [rdx +  0]
    mov [rdi +  0], rax
    .set k, 1
    .rept 127
        mov rax, [rsi + 8*k]
        sbb rax, [rdx + 8*k]
        mov [rdi + 8*k], rax
        .set k, k+1
    .endr
    setc al
    movzx rax, al
    ret


.global secsidh_internal_8191m78l338_uintbig_mul3_64
secsidh_internal_8191m78l338_uintbig_mul3_64:

    mulx r10, rax, [rsi +  0]
    mov [rdi +  0], rax

    mulx r11, rax, [rsi + 8]
    add  rax, r10
    mov [rdi + 8], rax

    mulx r10, rax, [rsi + 16]
    adcx rax, r11
    mov [rdi + 16], rax

    mulx r11, rax, [rsi + 24]
    adcx rax, r10
    mov [rdi + 24], rax

    mulx r10, rax, [rsi + 32]
    adcx rax, r11
    mov [rdi + 32], rax

    mulx r11, rax, [rsi + 40]
    adcx rax, r10
    mov [rdi + 40], rax

    mulx r10, rax, [rsi + 48]
    adcx rax, r11
    mov [rdi + 48], rax

    mulx r11, rax, [rsi + 56]
    adcx rax, r10
    mov [rdi + 56], rax

    mulx r10, rax, [rsi + 64]
    adcx rax, r11
    mov [rdi + 64], rax

    mulx r11, rax, [rsi + 72]
    adcx rax, r10
    mov [rdi + 72], rax

    mulx r10, rax, [rsi + 80]
    adcx rax, r11
    mov [rdi + 80], rax

    mulx r11, rax, [rsi + 88]
    adcx rax, r10
    mov [rdi + 88], rax

    mulx r10, rax, [rsi + 96]
    adcx rax, r11
    mov [rdi + 96], rax

    mulx r11, rax, [rsi + 104]
    adcx rax, r10
    mov [rdi + 104], rax

    mulx r10, rax, [rsi + 112]
    adcx rax, r11
    mov [rdi + 112], rax

    mulx r11, rax, [rsi + 120]
    adcx rax, r10
    mov [rdi + 120], rax

    mulx r10, rax, [rsi + 128]
    adcx rax, r11
    mov [rdi + 128], rax

    mulx r11, rax, [rsi + 136]
    adcx rax, r10
    mov [rdi + 136], rax

    mulx r10, rax, [rsi + 144]
    adcx rax, r11
    mov [rdi + 144], rax

    mulx r11, rax, [rsi + 152]
    adcx rax, r10
    mov [rdi + 152], rax

    mulx r10, rax, [rsi + 160]
    adcx rax, r11
    mov [rdi + 160], rax

    mulx r11, rax, [rsi + 168]
    adcx rax, r10
    mov [rdi + 168], rax

    mulx r10, rax, [rsi + 176]
    adcx rax, r11
    mov [rdi + 176], rax

    mulx r11, rax, [rsi + 184]
    adcx rax, r10
    mov [rdi + 184], rax

    mulx r10, rax, [rsi + 192]
    adcx rax, r11
    mov [rdi + 192], rax

    mulx r11, rax, [rsi + 200]
    adcx rax, r10
    mov [rdi + 200], rax

    mulx r10, rax, [rsi + 208]
    adcx rax, r11
    mov [rdi + 208], rax

    mulx r11, rax, [rsi + 216]
    adcx rax, r10
    mov [rdi + 216], rax

    mulx r10, rax, [rsi + 224]
    adcx rax, r11
    mov [rdi + 224], rax

    mulx r11, rax, [rsi + 232]
    adcx rax, r10
    mov [rdi + 232], rax

    mulx r10, rax, [rsi + 240]
    adcx rax, r11
    mov [rdi + 240], rax

    mulx r11, rax, [rsi + 248]
    adcx rax, r10
    mov [rdi + 248], rax

    mulx r10, rax, [rsi + 256]
    adcx rax, r11
    mov [rdi + 256], rax

    mulx r11, rax, [rsi + 264]
    adcx rax, r10
    mov [rdi + 264], rax

    mulx r10, rax, [rsi + 272]
    adcx rax, r11
    mov [rdi + 272], rax

    mulx r11, rax, [rsi + 280]
    adcx rax, r10
    mov [rdi + 280], rax

    mulx r10, rax, [rsi + 288]
    adcx rax, r11
    mov [rdi + 288], rax

    mulx r11, rax, [rsi + 296]
    adcx rax, r10
    mov [rdi + 296], rax

    mulx r10, rax, [rsi + 304]
    adcx rax, r11
    mov [rdi + 304], rax

    mulx r11, rax, [rsi + 312]
    adcx rax, r10
    mov [rdi + 312], rax

    mulx r10, rax, [rsi + 320]
    adcx rax, r11
    mov [rdi + 320], rax

    mulx r11, rax, [rsi + 328]
    adcx rax, r10
    mov [rdi + 328], rax

    mulx r10, rax, [rsi + 336]
    adcx rax, r11
    mov [rdi + 336], rax

    mulx r11, rax, [rsi + 344]
    adcx rax, r10
    mov [rdi + 344], rax

    mulx r10, rax, [rsi + 352]
    adcx rax, r11
    mov [rdi + 352], rax

    mulx r11, rax, [rsi + 360]
    adcx rax, r10
    mov [rdi + 360], rax

    mulx r10, rax, [rsi + 368]
    adcx rax, r11
    mov [rdi + 368], rax

    mulx r11, rax, [rsi + 376]
    adcx rax, r10
    mov [rdi + 376], rax

    mulx r10, rax, [rsi + 384]
    adcx rax, r11
    mov [rdi + 384], rax

    mulx r11, rax, [rsi + 392]
    adcx rax, r10
    mov [rdi + 392], rax

    mulx r10, rax, [rsi + 400]
    adcx rax, r11
    mov [rdi + 400], rax

    mulx r11, rax, [rsi + 408]
    adcx rax, r10
    mov [rdi + 408], rax

    mulx r10, rax, [rsi + 416]
    adcx rax, r11
    mov [rdi + 416], rax

    mulx r11, rax, [rsi + 424]
    adcx rax, r10
    mov [rdi + 424], rax

    mulx r10, rax, [rsi + 432]
    adcx rax, r11
    mov [rdi + 432], rax

    mulx r11, rax, [rsi + 440]
    adcx rax, r10
    mov [rdi + 440], rax

    mulx r10, rax, [rsi + 448]
    adcx rax, r11
    mov [rdi + 448], rax

    mulx r11, rax, [rsi + 456]
    adcx rax, r10
    mov [rdi + 456], rax

    mulx r10, rax, [rsi + 464]
    adcx rax, r11
    mov [rdi + 464], rax

    mulx r11, rax, [rsi + 472]
    adcx rax, r10
    mov [rdi + 472], rax

    mulx r10, rax, [rsi + 480]
    adcx rax, r11
    mov [rdi + 480], rax

    mulx r11, rax, [rsi + 488]
    adcx rax, r10
    mov [rdi + 488], rax

    mulx r10, rax, [rsi + 496]
    adcx rax, r11
    mov [rdi + 496], rax

    mulx r11, rax, [rsi + 504]
    adcx rax, r10
    mov [rdi + 504], rax

    mulx r10, rax, [rsi + 512]
    adcx rax, r11
    mov [rdi + 512], rax

    mulx r11, rax, [rsi + 520]
    adcx rax, r10
    mov [rdi + 520], rax

    mulx r10, rax, [rsi + 528]
    adcx rax, r11
    mov [rdi + 528], rax

    mulx r11, rax, [rsi + 536]
    adcx rax, r10
    mov [rdi + 536], rax

    mulx r10, rax, [rsi + 544]
    adcx rax, r11
    mov [rdi + 544], rax

    mulx r11, rax, [rsi + 552]
    adcx rax, r10
    mov [rdi + 552], rax

    mulx r10, rax, [rsi + 560]
    adcx rax, r11
    mov [rdi + 560], rax

    mulx r11, rax, [rsi + 568]
    adcx rax, r10
    mov [rdi + 568], rax

    mulx r10, rax, [rsi + 576]
    adcx rax, r11
    mov [rdi + 576], rax

    mulx r11, rax, [rsi + 584]
    adcx rax, r10
    mov [rdi + 584], rax

    mulx r10, rax, [rsi + 592]
    adcx rax, r11
    mov [rdi + 592], rax

    mulx r11, rax, [rsi + 600]
    adcx rax, r10
    mov [rdi + 600], rax

    mulx r10, rax, [rsi + 608]
    adcx rax, r11
    mov [rdi + 608], rax

    mulx r11, rax, [rsi + 616]
    adcx rax, r10
    mov [rdi + 616], rax

    mulx r10, rax, [rsi + 624]
    adcx rax, r11
    mov [rdi + 624], rax

    mulx r11, rax, [rsi + 632]
    adcx rax, r10
    mov [rdi + 632], rax

    mulx r10, rax, [rsi + 640]
    adcx rax, r11
    mov [rdi + 640], rax

    mulx r11, rax, [rsi + 648]
    adcx rax, r10
    mov [rdi + 648], rax

    mulx r10, rax, [rsi + 656]
    adcx rax, r11
    mov [rdi + 656], rax

    mulx r11, rax, [rsi + 664]
    adcx rax, r10
    mov [rdi + 664], rax

    mulx r10, rax, [rsi + 672]
    adcx rax, r11
    mov [rdi + 672], rax

    mulx r11, rax, [rsi + 680]
    adcx rax, r10
    mov [rdi + 680], rax

    mulx r10, rax, [rsi + 688]
    adcx rax, r11
    mov [rdi + 688], rax

    mulx r11, rax, [rsi + 696]
    adcx rax, r10
    mov [rdi + 696], rax

    mulx r10, rax, [rsi + 704]
    adcx rax, r11
    mov [rdi + 704], rax

    mulx r11, rax, [rsi + 712]
    adcx rax, r10
    mov [rdi + 712], rax

    mulx r10, rax, [rsi + 720]
    adcx rax, r11
    mov [rdi + 720], rax

    mulx r11, rax, [rsi + 728]
    adcx rax, r10
    mov [rdi + 728], rax

    mulx r10, rax, [rsi + 736]
    adcx rax, r11
    mov [rdi + 736], rax

    mulx r11, rax, [rsi + 744]
    adcx rax, r10
    mov [rdi + 744], rax

    mulx r10, rax, [rsi + 752]
    adcx rax, r11
    mov [rdi + 752], rax

    mulx r11, rax, [rsi + 760]
    adcx rax, r10
    mov [rdi + 760], rax

    mulx r10, rax, [rsi + 768]
    adcx rax, r11
    mov [rdi + 768], rax

    mulx r11, rax, [rsi + 776]
    adcx rax, r10
    mov [rdi + 776], rax

    mulx r10, rax, [rsi + 784]
    adcx rax, r11
    mov [rdi + 784], rax

    mulx r11, rax, [rsi + 792]
    adcx rax, r10
    mov [rdi + 792], rax

    mulx r10, rax, [rsi + 800]
    adcx rax, r11
    mov [rdi + 800], rax

    mulx r11, rax, [rsi + 808]
    adcx rax, r10
    mov [rdi + 808], rax

    mulx r10, rax, [rsi + 816]
    adcx rax, r11
    mov [rdi + 816], rax

    mulx r11, rax, [rsi + 824]
    adcx rax, r10
    mov [rdi + 824], rax

    mulx r10, rax, [rsi + 832]
    adcx rax, r11
    mov [rdi + 832], rax

    mulx r11, rax, [rsi + 840]
    adcx rax, r10
    mov [rdi + 840], rax

    mulx r10, rax, [rsi + 848]
    adcx rax, r11
    mov [rdi + 848], rax

    mulx r11, rax, [rsi + 856]
    adcx rax, r10
    mov [rdi + 856], rax

    mulx r10, rax, [rsi + 864]
    adcx rax, r11
    mov [rdi + 864], rax

    mulx r11, rax, [rsi + 872]
    adcx rax, r10
    mov [rdi + 872], rax

    mulx r10, rax, [rsi + 880]
    adcx rax, r11
    mov [rdi + 880], rax

    mulx r11, rax, [rsi + 888]
    adcx rax, r10
    mov [rdi + 888], rax

    mulx r10, rax, [rsi + 896]
    adcx rax, r11
    mov [rdi + 896], rax

    mulx r11, rax, [rsi + 904]
    adcx rax, r10
    mov [rdi + 904], rax

    mulx r10, rax, [rsi + 912]
    adcx rax, r11
    mov [rdi + 912], rax

    mulx r11, rax, [rsi + 920]
    adcx rax, r10
    mov [rdi + 920], rax

    mulx r10, rax, [rsi + 928]
    adcx rax, r11
    mov [rdi + 928], rax

    mulx r11, rax, [rsi + 936]
    adcx rax, r10
    mov [rdi + 936], rax

    mulx r10, rax, [rsi + 944]
    adcx rax, r11
    mov [rdi + 944], rax

    mulx r11, rax, [rsi + 952]
    adcx rax, r10
    mov [rdi + 952], rax

    mulx r10, rax, [rsi + 960]
    adcx rax, r11
    mov [rdi + 960], rax

    mulx r11, rax, [rsi + 968]
    adcx rax, r10
    mov [rdi + 968], rax

    mulx r10, rax, [rsi + 976]
    adcx rax, r11
    mov [rdi + 976], rax

    mulx r11, rax, [rsi + 984]
    adcx rax, r10
    mov [rdi + 984], rax

    mulx r10, rax, [rsi + 992]
    adcx rax, r11
    mov [rdi + 992], rax

    mulx r11, rax, [rsi + 1000]
    adcx rax, r10
    mov [rdi + 1000], rax

    mulx r10, rax, [rsi + 1008]
    adcx rax, r11
    mov [rdi + 1008], rax

    mulx r11, rax, [rsi + 1016]
    adcx rax, r10
    mov [rdi + 1016], rax

    ret
