/* DO NOT EDIT! generated by ./autogen */

.intel_syntax noprefix

#include "uintbig_namespace.h"

.section .rodata

.global secsidh_internal_9215m85l389_uintbig_1
secsidh_internal_9215m85l389_uintbig_1:
    .quad 1, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0

.global secsidh_internal_9215m85l389_uintbig_1_ctidh
secsidh_internal_9215m85l389_uintbig_1_ctidh:
    .quad 1, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0    

.global secsidh_internal_9215m85l389_uintbig_p
secsidh_internal_9215m85l389_uintbig_p:
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0x2ec17140ffffffff, 0x58829a4749bfa0d2, 0x6e1c47467499d375, 0xa433acae72c1d8b4
    .quad 0xcf5cd95ce82a5c14, 0xe60dbdfab3ffd04c, 0x3671b6b3cd0f7e58, 0x6bd02b7fce0f4e75
    .quad 0x90f24807b4b7af9c, 0x4f2cec0ce0241b0f, 0xdae4ab0857a44847, 0xda2831ee87cbe75d
    .quad 0xe72faf27764e4cbe, 0xaaf62c413e6e47f1, 0xbbffc6e78dbc2da3, 0x4fa19216246934d0
    .quad 0x53d89ce34fc62bd1, 0xc08ace12cf11f198, 0xa42fa468f0346202, 0xf3a1ace18417ab2f
    .quad 0xfb69d6e1f8ab9389, 0x233f0419f2f959c2, 0x40b2d4dd4b30387a, 0xa84638104a9ab888
    .quad 0xca0cc59ece014f78, 0xd3997f280ff40cad, 0x80fc6d8b97015d3e, 0x1f4be77febba6733
    .quad 0xf1dd3386ac13f6a7, 0xd6544289e2b3acd6, 0x2e4ebaa44bf213a5, 0xd231097e09fe98fd
    .quad 0xc69c26ac0032fe40, 0x520c24a33c2a46c7, 0x5e1bcdc39f4c8b8f, 0x5559a516cbf6d850
    .quad 0x6ad4a3e4198b3c5c, 0x38022e0311f218e8, 0xf3264c72939c7e55, 0x3c0df145b5bd51bc
    .quad 0x628a478fa5124829, 0x07e5fa4319c3877a, 0xae8b7d05a9a30981, 0x5977ac2cace90f15
    .quad 0x0d8ecfcbde4d6b71, 0xa96937dc65c53548, 0xa9255f2dffef2a9d, 0x1b9060660751b405
    .quad 0x9777ac37e208f29a, 0xe021aac821b5fd14, 0x4363cfaf112793a5, 0x3419dcb6afda0e09
    .quad 0x3affec566c311e95, 0xd1e15edccc3ea709, 0x9d000e8c5ee1b5b6, 0x8fc1951a0b63aa28
    .quad 0xe74515e327c95380, 0x15281c20ef5e3b77, 0xe841e5f92ae94c9c, 0x4d0dd48d039de3a7

.global secsidh_internal_9215m85l389_uintbig_four_sqrt_p
secsidh_internal_9215m85l389_uintbig_four_sqrt_p:
    .quad 0xbbbcca96ee5d1770, 0x7ff8344b96288ccd, 0x3e441927106e3e41, 0x6b8669abd23c46a3
    .quad 0x9a16e20a204c2dd4, 0x2c4fdf1a692d8f7b, 0xb4fa2c5134e9c039, 0xfdb9a27ff24f715a
    .quad 0x0685a89778edf52a, 0xbb7d13d45e300058, 0x2d419536778c7ab5, 0xd968da98565aeb0b
    .quad 0xf3c9e1839f101bdd, 0x65110c2f62d91e0d, 0xf38c2de245ae60c6, 0x31d1baaa67389f2c
    .quad 0xb37cafc87406aa7a, 0xcfc3cce1700bc45d, 0x900f01c62ac7dfd6, 0x000d2b6c95eebf0d
    .quad 0xff05821e83af7638, 0xaae6fea46214cc99, 0x8d4844d28b1e351a, 0x9628779b3cadc2b2
    .quad 0xc9a7d8b8743fcfa1, 0x15e0f20225b95bd1, 0xde54b483c25f3dc1, 0xc64cc5a419610f8e
    .quad 0x9e8189f6e87f3523, 0xf4e5fa60a76c4287, 0xd4fbe46eaea04edd, 0x050692a8304ffc82
    .quad 0x82d8bf5b862fd927, 0xfeea98e476f36e97, 0x0ac8d0f24598eabd, 0x19e17b8962b7e30a
    .quad 0x5f8f29879e7399cf, 0x8cdd61cf727c5e3a, 0x0283a61c627c1b4c, 0x55f7346665e24516
    .quad 0x80b0b8c65b11b63e, 0xc94c007de955ac4b, 0x2cea179f048752c7, 0x59b92565e895f656
    .quad 0xe115f078aeec68ac, 0xd8097e7a67a53234, 0x9fe99411b05831c4, 0x0d42b85b2ff1846b
    .quad 0x04ca79aae7dc1fc7, 0x79d5ccfef1824e9f, 0x25c4da2aaca0811a, 0x5fca62e0d89c4af5
    .quad 0xf7d656cbd178c1ae, 0x690c371257cde024, 0x8aa1970a2e7915bb, 0x34e1caa7a2bfb533
    .quad 0xba8a89aa2c100bd3, 0x86aece8ddfbb8ae3, 0xdd76f6a91e174c7d, 0x0e25866e23b7c945
    .quad 0xd5c8090c35cd7ac1, 0x37623f29a5b854bb, 0x8d5f1d7c369f229a, 0x3f79fd2e88fbbc80
    .quad 0xe00f3eeaa97513ac, 0xee50c34ead172f60, 0x15e46498cd4912a0, 0x61f6afd09fb80859
    .quad 0xef9b8ae7b9c7ebbd, 0x593846662fe9cecc, 0x82d8332c63f66cbc, 0x31cb716dc74d963a
    .quad 2, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0

.section .text

.global secsidh_internal_9215m85l389_uintbig_set
secsidh_internal_9215m85l389_uintbig_set:
    cld
    mov rax, rsi
    stosq
    xor rax, rax
    mov rcx, 143
    rep stosq
    ret


.global secsidh_internal_9215m85l389_uintbig_bit
secsidh_internal_9215m85l389_uintbig_bit:
    mov rcx, rsi
    and rcx, 0x3f
    shr rsi, 6
    mov rax, [rdi + 8*rsi]
    shr rax, cl
    and rax, 1
    ret


.global secsidh_internal_9215m85l389_uintbig_add
secsidh_internal_9215m85l389_uintbig_add:
    mov rax, [rsi +  0]
    add rax, [rdx +  0]
    mov [rdi +  0], rax
    .set k, 1
    .rept 143
        mov rax, [rsi + 8*k]
        adc rax, [rdx + 8*k]
        mov [rdi + 8*k], rax
        .set k, k+1
    .endr
    setc al
    movzx rax, al
    ret

.global secsidh_internal_9215m85l389_uintbig_sub3
secsidh_internal_9215m85l389_uintbig_sub3:
.global secsidh_internal_9215m85l389_uintbig_sub
secsidh_internal_9215m85l389_uintbig_sub:
    mov rax, [rsi +  0]
    sub rax, [rdx +  0]
    mov [rdi +  0], rax
    .set k, 1
    .rept 143
        mov rax, [rsi + 8*k]
        sbb rax, [rdx + 8*k]
        mov [rdi + 8*k], rax
        .set k, k+1
    .endr
    setc al
    movzx rax, al
    ret


.global secsidh_internal_9215m85l389_uintbig_mul3_64
secsidh_internal_9215m85l389_uintbig_mul3_64:

    mulx r10, rax, [rsi +  0]
    mov [rdi +  0], rax

    mulx r11, rax, [rsi + 8]
    add  rax, r10
    mov [rdi + 8], rax

    mulx r10, rax, [rsi + 16]
    adcx rax, r11
    mov [rdi + 16], rax

    mulx r11, rax, [rsi + 24]
    adcx rax, r10
    mov [rdi + 24], rax

    mulx r10, rax, [rsi + 32]
    adcx rax, r11
    mov [rdi + 32], rax

    mulx r11, rax, [rsi + 40]
    adcx rax, r10
    mov [rdi + 40], rax

    mulx r10, rax, [rsi + 48]
    adcx rax, r11
    mov [rdi + 48], rax

    mulx r11, rax, [rsi + 56]
    adcx rax, r10
    mov [rdi + 56], rax

    mulx r10, rax, [rsi + 64]
    adcx rax, r11
    mov [rdi + 64], rax

    mulx r11, rax, [rsi + 72]
    adcx rax, r10
    mov [rdi + 72], rax

    mulx r10, rax, [rsi + 80]
    adcx rax, r11
    mov [rdi + 80], rax

    mulx r11, rax, [rsi + 88]
    adcx rax, r10
    mov [rdi + 88], rax

    mulx r10, rax, [rsi + 96]
    adcx rax, r11
    mov [rdi + 96], rax

    mulx r11, rax, [rsi + 104]
    adcx rax, r10
    mov [rdi + 104], rax

    mulx r10, rax, [rsi + 112]
    adcx rax, r11
    mov [rdi + 112], rax

    mulx r11, rax, [rsi + 120]
    adcx rax, r10
    mov [rdi + 120], rax

    mulx r10, rax, [rsi + 128]
    adcx rax, r11
    mov [rdi + 128], rax

    mulx r11, rax, [rsi + 136]
    adcx rax, r10
    mov [rdi + 136], rax

    mulx r10, rax, [rsi + 144]
    adcx rax, r11
    mov [rdi + 144], rax

    mulx r11, rax, [rsi + 152]
    adcx rax, r10
    mov [rdi + 152], rax

    mulx r10, rax, [rsi + 160]
    adcx rax, r11
    mov [rdi + 160], rax

    mulx r11, rax, [rsi + 168]
    adcx rax, r10
    mov [rdi + 168], rax

    mulx r10, rax, [rsi + 176]
    adcx rax, r11
    mov [rdi + 176], rax

    mulx r11, rax, [rsi + 184]
    adcx rax, r10
    mov [rdi + 184], rax

    mulx r10, rax, [rsi + 192]
    adcx rax, r11
    mov [rdi + 192], rax

    mulx r11, rax, [rsi + 200]
    adcx rax, r10
    mov [rdi + 200], rax

    mulx r10, rax, [rsi + 208]
    adcx rax, r11
    mov [rdi + 208], rax

    mulx r11, rax, [rsi + 216]
    adcx rax, r10
    mov [rdi + 216], rax

    mulx r10, rax, [rsi + 224]
    adcx rax, r11
    mov [rdi + 224], rax

    mulx r11, rax, [rsi + 232]
    adcx rax, r10
    mov [rdi + 232], rax

    mulx r10, rax, [rsi + 240]
    adcx rax, r11
    mov [rdi + 240], rax

    mulx r11, rax, [rsi + 248]
    adcx rax, r10
    mov [rdi + 248], rax

    mulx r10, rax, [rsi + 256]
    adcx rax, r11
    mov [rdi + 256], rax

    mulx r11, rax, [rsi + 264]
    adcx rax, r10
    mov [rdi + 264], rax

    mulx r10, rax, [rsi + 272]
    adcx rax, r11
    mov [rdi + 272], rax

    mulx r11, rax, [rsi + 280]
    adcx rax, r10
    mov [rdi + 280], rax

    mulx r10, rax, [rsi + 288]
    adcx rax, r11
    mov [rdi + 288], rax

    mulx r11, rax, [rsi + 296]
    adcx rax, r10
    mov [rdi + 296], rax

    mulx r10, rax, [rsi + 304]
    adcx rax, r11
    mov [rdi + 304], rax

    mulx r11, rax, [rsi + 312]
    adcx rax, r10
    mov [rdi + 312], rax

    mulx r10, rax, [rsi + 320]
    adcx rax, r11
    mov [rdi + 320], rax

    mulx r11, rax, [rsi + 328]
    adcx rax, r10
    mov [rdi + 328], rax

    mulx r10, rax, [rsi + 336]
    adcx rax, r11
    mov [rdi + 336], rax

    mulx r11, rax, [rsi + 344]
    adcx rax, r10
    mov [rdi + 344], rax

    mulx r10, rax, [rsi + 352]
    adcx rax, r11
    mov [rdi + 352], rax

    mulx r11, rax, [rsi + 360]
    adcx rax, r10
    mov [rdi + 360], rax

    mulx r10, rax, [rsi + 368]
    adcx rax, r11
    mov [rdi + 368], rax

    mulx r11, rax, [rsi + 376]
    adcx rax, r10
    mov [rdi + 376], rax

    mulx r10, rax, [rsi + 384]
    adcx rax, r11
    mov [rdi + 384], rax

    mulx r11, rax, [rsi + 392]
    adcx rax, r10
    mov [rdi + 392], rax

    mulx r10, rax, [rsi + 400]
    adcx rax, r11
    mov [rdi + 400], rax

    mulx r11, rax, [rsi + 408]
    adcx rax, r10
    mov [rdi + 408], rax

    mulx r10, rax, [rsi + 416]
    adcx rax, r11
    mov [rdi + 416], rax

    mulx r11, rax, [rsi + 424]
    adcx rax, r10
    mov [rdi + 424], rax

    mulx r10, rax, [rsi + 432]
    adcx rax, r11
    mov [rdi + 432], rax

    mulx r11, rax, [rsi + 440]
    adcx rax, r10
    mov [rdi + 440], rax

    mulx r10, rax, [rsi + 448]
    adcx rax, r11
    mov [rdi + 448], rax

    mulx r11, rax, [rsi + 456]
    adcx rax, r10
    mov [rdi + 456], rax

    mulx r10, rax, [rsi + 464]
    adcx rax, r11
    mov [rdi + 464], rax

    mulx r11, rax, [rsi + 472]
    adcx rax, r10
    mov [rdi + 472], rax

    mulx r10, rax, [rsi + 480]
    adcx rax, r11
    mov [rdi + 480], rax

    mulx r11, rax, [rsi + 488]
    adcx rax, r10
    mov [rdi + 488], rax

    mulx r10, rax, [rsi + 496]
    adcx rax, r11
    mov [rdi + 496], rax

    mulx r11, rax, [rsi + 504]
    adcx rax, r10
    mov [rdi + 504], rax

    mulx r10, rax, [rsi + 512]
    adcx rax, r11
    mov [rdi + 512], rax

    mulx r11, rax, [rsi + 520]
    adcx rax, r10
    mov [rdi + 520], rax

    mulx r10, rax, [rsi + 528]
    adcx rax, r11
    mov [rdi + 528], rax

    mulx r11, rax, [rsi + 536]
    adcx rax, r10
    mov [rdi + 536], rax

    mulx r10, rax, [rsi + 544]
    adcx rax, r11
    mov [rdi + 544], rax

    mulx r11, rax, [rsi + 552]
    adcx rax, r10
    mov [rdi + 552], rax

    mulx r10, rax, [rsi + 560]
    adcx rax, r11
    mov [rdi + 560], rax

    mulx r11, rax, [rsi + 568]
    adcx rax, r10
    mov [rdi + 568], rax

    mulx r10, rax, [rsi + 576]
    adcx rax, r11
    mov [rdi + 576], rax

    mulx r11, rax, [rsi + 584]
    adcx rax, r10
    mov [rdi + 584], rax

    mulx r10, rax, [rsi + 592]
    adcx rax, r11
    mov [rdi + 592], rax

    mulx r11, rax, [rsi + 600]
    adcx rax, r10
    mov [rdi + 600], rax

    mulx r10, rax, [rsi + 608]
    adcx rax, r11
    mov [rdi + 608], rax

    mulx r11, rax, [rsi + 616]
    adcx rax, r10
    mov [rdi + 616], rax

    mulx r10, rax, [rsi + 624]
    adcx rax, r11
    mov [rdi + 624], rax

    mulx r11, rax, [rsi + 632]
    adcx rax, r10
    mov [rdi + 632], rax

    mulx r10, rax, [rsi + 640]
    adcx rax, r11
    mov [rdi + 640], rax

    mulx r11, rax, [rsi + 648]
    adcx rax, r10
    mov [rdi + 648], rax

    mulx r10, rax, [rsi + 656]
    adcx rax, r11
    mov [rdi + 656], rax

    mulx r11, rax, [rsi + 664]
    adcx rax, r10
    mov [rdi + 664], rax

    mulx r10, rax, [rsi + 672]
    adcx rax, r11
    mov [rdi + 672], rax

    mulx r11, rax, [rsi + 680]
    adcx rax, r10
    mov [rdi + 680], rax

    mulx r10, rax, [rsi + 688]
    adcx rax, r11
    mov [rdi + 688], rax

    mulx r11, rax, [rsi + 696]
    adcx rax, r10
    mov [rdi + 696], rax

    mulx r10, rax, [rsi + 704]
    adcx rax, r11
    mov [rdi + 704], rax

    mulx r11, rax, [rsi + 712]
    adcx rax, r10
    mov [rdi + 712], rax

    mulx r10, rax, [rsi + 720]
    adcx rax, r11
    mov [rdi + 720], rax

    mulx r11, rax, [rsi + 728]
    adcx rax, r10
    mov [rdi + 728], rax

    mulx r10, rax, [rsi + 736]
    adcx rax, r11
    mov [rdi + 736], rax

    mulx r11, rax, [rsi + 744]
    adcx rax, r10
    mov [rdi + 744], rax

    mulx r10, rax, [rsi + 752]
    adcx rax, r11
    mov [rdi + 752], rax

    mulx r11, rax, [rsi + 760]
    adcx rax, r10
    mov [rdi + 760], rax

    mulx r10, rax, [rsi + 768]
    adcx rax, r11
    mov [rdi + 768], rax

    mulx r11, rax, [rsi + 776]
    adcx rax, r10
    mov [rdi + 776], rax

    mulx r10, rax, [rsi + 784]
    adcx rax, r11
    mov [rdi + 784], rax

    mulx r11, rax, [rsi + 792]
    adcx rax, r10
    mov [rdi + 792], rax

    mulx r10, rax, [rsi + 800]
    adcx rax, r11
    mov [rdi + 800], rax

    mulx r11, rax, [rsi + 808]
    adcx rax, r10
    mov [rdi + 808], rax

    mulx r10, rax, [rsi + 816]
    adcx rax, r11
    mov [rdi + 816], rax

    mulx r11, rax, [rsi + 824]
    adcx rax, r10
    mov [rdi + 824], rax

    mulx r10, rax, [rsi + 832]
    adcx rax, r11
    mov [rdi + 832], rax

    mulx r11, rax, [rsi + 840]
    adcx rax, r10
    mov [rdi + 840], rax

    mulx r10, rax, [rsi + 848]
    adcx rax, r11
    mov [rdi + 848], rax

    mulx r11, rax, [rsi + 856]
    adcx rax, r10
    mov [rdi + 856], rax

    mulx r10, rax, [rsi + 864]
    adcx rax, r11
    mov [rdi + 864], rax

    mulx r11, rax, [rsi + 872]
    adcx rax, r10
    mov [rdi + 872], rax

    mulx r10, rax, [rsi + 880]
    adcx rax, r11
    mov [rdi + 880], rax

    mulx r11, rax, [rsi + 888]
    adcx rax, r10
    mov [rdi + 888], rax

    mulx r10, rax, [rsi + 896]
    adcx rax, r11
    mov [rdi + 896], rax

    mulx r11, rax, [rsi + 904]
    adcx rax, r10
    mov [rdi + 904], rax

    mulx r10, rax, [rsi + 912]
    adcx rax, r11
    mov [rdi + 912], rax

    mulx r11, rax, [rsi + 920]
    adcx rax, r10
    mov [rdi + 920], rax

    mulx r10, rax, [rsi + 928]
    adcx rax, r11
    mov [rdi + 928], rax

    mulx r11, rax, [rsi + 936]
    adcx rax, r10
    mov [rdi + 936], rax

    mulx r10, rax, [rsi + 944]
    adcx rax, r11
    mov [rdi + 944], rax

    mulx r11, rax, [rsi + 952]
    adcx rax, r10
    mov [rdi + 952], rax

    mulx r10, rax, [rsi + 960]
    adcx rax, r11
    mov [rdi + 960], rax

    mulx r11, rax, [rsi + 968]
    adcx rax, r10
    mov [rdi + 968], rax

    mulx r10, rax, [rsi + 976]
    adcx rax, r11
    mov [rdi + 976], rax

    mulx r11, rax, [rsi + 984]
    adcx rax, r10
    mov [rdi + 984], rax

    mulx r10, rax, [rsi + 992]
    adcx rax, r11
    mov [rdi + 992], rax

    mulx r11, rax, [rsi + 1000]
    adcx rax, r10
    mov [rdi + 1000], rax

    mulx r10, rax, [rsi + 1008]
    adcx rax, r11
    mov [rdi + 1008], rax

    mulx r11, rax, [rsi + 1016]
    adcx rax, r10
    mov [rdi + 1016], rax

    mulx r10, rax, [rsi + 1024]
    adcx rax, r11
    mov [rdi + 1024], rax

    mulx r11, rax, [rsi + 1032]
    adcx rax, r10
    mov [rdi + 1032], rax

    mulx r10, rax, [rsi + 1040]
    adcx rax, r11
    mov [rdi + 1040], rax

    mulx r11, rax, [rsi + 1048]
    adcx rax, r10
    mov [rdi + 1048], rax

    mulx r10, rax, [rsi + 1056]
    adcx rax, r11
    mov [rdi + 1056], rax

    mulx r11, rax, [rsi + 1064]
    adcx rax, r10
    mov [rdi + 1064], rax

    mulx r10, rax, [rsi + 1072]
    adcx rax, r11
    mov [rdi + 1072], rax

    mulx r11, rax, [rsi + 1080]
    adcx rax, r10
    mov [rdi + 1080], rax

    mulx r10, rax, [rsi + 1088]
    adcx rax, r11
    mov [rdi + 1088], rax

    mulx r11, rax, [rsi + 1096]
    adcx rax, r10
    mov [rdi + 1096], rax

    mulx r10, rax, [rsi + 1104]
    adcx rax, r11
    mov [rdi + 1104], rax

    mulx r11, rax, [rsi + 1112]
    adcx rax, r10
    mov [rdi + 1112], rax

    mulx r10, rax, [rsi + 1120]
    adcx rax, r11
    mov [rdi + 1120], rax

    mulx r11, rax, [rsi + 1128]
    adcx rax, r10
    mov [rdi + 1128], rax

    mulx r10, rax, [rsi + 1136]
    adcx rax, r11
    mov [rdi + 1136], rax

    mulx r11, rax, [rsi + 1144]
    adcx rax, r10
    mov [rdi + 1144], rax

    ret
