/* DO NOT EDIT! generated by ./autogen */

.intel_syntax noprefix

#include "uintbig_namespace.h"

.section .rodata

.global secsidh_internal_2047m1l226_uintbig_1
secsidh_internal_2047m1l226_uintbig_1:
    .quad 1, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0

.global secsidh_internal_2047m1l226_uintbig_1_ctidh
secsidh_internal_2047m1l226_uintbig_1_ctidh:
    .quad 1, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0    

.global secsidh_internal_2047m1l226_uintbig_p
secsidh_internal_2047m1l226_uintbig_p:
    .quad 0xffffffffffffffff, 0xc90a04ffffffffff, 0xfc70c3714d157138, 0xc5a05e7d325440ec
    .quad 0xf61fe1a2e6d6cac6, 0x1a549b7f4b8f58f1, 0xf6d3630a6ebae5ed, 0x478af769ae62b6e0
    .quad 0x7835f78ebc56ce0c, 0xd51310e46e8c2b09, 0xffc6c6b2579b25d1, 0x93f4fab37d61640d
    .quad 0xac53715e3b7b9962, 0xa90481e7927800a6, 0x89a678df7aae625b, 0x844d51d759b0c530
    .quad 0x05816da706eb3cab, 0x457afa1ae8c5352a, 0x90c340c95add5f8c, 0xb543b329bed97c94
    .quad 0xac0073a2b919b0a4, 0x6c0e7aab1bf721df, 0x241fe343116b3177, 0x0ce8ad54d154c156
    .quad 0x82af03859d69962d, 0x9c3c0fc3740c26d8, 0xdebd472aa103a02b, 0x25d9e24a0748378b
    .quad 0x9c85afe27f67725f, 0xeff9ff84c9b3b1b4, 0x26bb94dc36fd0732, 0x4f49aaf26e4aefb6

.global secsidh_internal_2047m1l226_uintbig_four_sqrt_p
secsidh_internal_2047m1l226_uintbig_four_sqrt_p:
    .quad 0x93b2ff9ac8367fdf, 0x5e84996ca35238ff, 0x5641d33e3187af67, 0x2867f96a5366cccd
    .quad 0xca361b9cfad1b689, 0x8b9a5239dfb3f995, 0xfed4be5314e42402, 0xc2a350eec729aa5d
    .quad 0x3937178474ef3d64, 0x4705ab82965806fa, 0x34d6eeb730e79aab, 0xba5351474bc2b059
    .quad 0x51ba37ca74a5d55f, 0x732c50339c04f5f0, 0xf9d7989059901114, 0x39e129315e51828e
    .quad 2, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0

.section .text

.global secsidh_internal_2047m1l226_uintbig_set
secsidh_internal_2047m1l226_uintbig_set:
    cld
    mov rax, rsi
    stosq
    xor rax, rax
    mov rcx, 31
    rep stosq
    ret


.global secsidh_internal_2047m1l226_uintbig_bit
secsidh_internal_2047m1l226_uintbig_bit:
    mov rcx, rsi
    and rcx, 0x3f
    shr rsi, 6
    mov rax, [rdi + 8*rsi]
    shr rax, cl
    and rax, 1
    ret


.global secsidh_internal_2047m1l226_uintbig_add
secsidh_internal_2047m1l226_uintbig_add:
    mov rax, [rsi +  0]
    add rax, [rdx +  0]
    mov [rdi +  0], rax
    .set k, 1
    .rept 31
        mov rax, [rsi + 8*k]
        adc rax, [rdx + 8*k]
        mov [rdi + 8*k], rax
        .set k, k+1
    .endr
    setc al
    movzx rax, al
    ret

.global secsidh_internal_2047m1l226_uintbig_sub3
secsidh_internal_2047m1l226_uintbig_sub3:
.global secsidh_internal_2047m1l226_uintbig_sub
secsidh_internal_2047m1l226_uintbig_sub:
    mov rax, [rsi +  0]
    sub rax, [rdx +  0]
    mov [rdi +  0], rax
    .set k, 1
    .rept 31
        mov rax, [rsi + 8*k]
        sbb rax, [rdx + 8*k]
        mov [rdi + 8*k], rax
        .set k, k+1
    .endr
    setc al
    movzx rax, al
    ret


.global secsidh_internal_2047m1l226_uintbig_mul3_64
secsidh_internal_2047m1l226_uintbig_mul3_64:

    mulx r10, rax, [rsi +  0]
    mov [rdi +  0], rax

    mulx r11, rax, [rsi + 8]
    add  rax, r10
    mov [rdi + 8], rax

    mulx r10, rax, [rsi + 16]
    adcx rax, r11
    mov [rdi + 16], rax

    mulx r11, rax, [rsi + 24]
    adcx rax, r10
    mov [rdi + 24], rax

    mulx r10, rax, [rsi + 32]
    adcx rax, r11
    mov [rdi + 32], rax

    mulx r11, rax, [rsi + 40]
    adcx rax, r10
    mov [rdi + 40], rax

    mulx r10, rax, [rsi + 48]
    adcx rax, r11
    mov [rdi + 48], rax

    mulx r11, rax, [rsi + 56]
    adcx rax, r10
    mov [rdi + 56], rax

    mulx r10, rax, [rsi + 64]
    adcx rax, r11
    mov [rdi + 64], rax

    mulx r11, rax, [rsi + 72]
    adcx rax, r10
    mov [rdi + 72], rax

    mulx r10, rax, [rsi + 80]
    adcx rax, r11
    mov [rdi + 80], rax

    mulx r11, rax, [rsi + 88]
    adcx rax, r10
    mov [rdi + 88], rax

    mulx r10, rax, [rsi + 96]
    adcx rax, r11
    mov [rdi + 96], rax

    mulx r11, rax, [rsi + 104]
    adcx rax, r10
    mov [rdi + 104], rax

    mulx r10, rax, [rsi + 112]
    adcx rax, r11
    mov [rdi + 112], rax

    mulx r11, rax, [rsi + 120]
    adcx rax, r10
    mov [rdi + 120], rax

    mulx r10, rax, [rsi + 128]
    adcx rax, r11
    mov [rdi + 128], rax

    mulx r11, rax, [rsi + 136]
    adcx rax, r10
    mov [rdi + 136], rax

    mulx r10, rax, [rsi + 144]
    adcx rax, r11
    mov [rdi + 144], rax

    mulx r11, rax, [rsi + 152]
    adcx rax, r10
    mov [rdi + 152], rax

    mulx r10, rax, [rsi + 160]
    adcx rax, r11
    mov [rdi + 160], rax

    mulx r11, rax, [rsi + 168]
    adcx rax, r10
    mov [rdi + 168], rax

    mulx r10, rax, [rsi + 176]
    adcx rax, r11
    mov [rdi + 176], rax

    mulx r11, rax, [rsi + 184]
    adcx rax, r10
    mov [rdi + 184], rax

    mulx r10, rax, [rsi + 192]
    adcx rax, r11
    mov [rdi + 192], rax

    mulx r11, rax, [rsi + 200]
    adcx rax, r10
    mov [rdi + 200], rax

    mulx r10, rax, [rsi + 208]
    adcx rax, r11
    mov [rdi + 208], rax

    mulx r11, rax, [rsi + 216]
    adcx rax, r10
    mov [rdi + 216], rax

    mulx r10, rax, [rsi + 224]
    adcx rax, r11
    mov [rdi + 224], rax

    mulx r11, rax, [rsi + 232]
    adcx rax, r10
    mov [rdi + 232], rax

    mulx r10, rax, [rsi + 240]
    adcx rax, r11
    mov [rdi + 240], rax

    mulx r11, rax, [rsi + 248]
    adcx rax, r10
    mov [rdi + 248], rax

    ret
